[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate --no-input"

[deploy]
startCommand = "gunicorn pune_color_festival.wsgi:application --timeout 120 --workers 2"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
